name: Reusable Terraform

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

      action:
        required: false
        type: string
        default: plan

      aws_region:
        required: false
        type: string
        default: us-east-1

      terraform_version:
        required: false
        type: string
        default: "1.10.5"

      role_to_assume:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Test AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: terraform plan

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve